# This workflow sends a message whenever an issue/issue comment is created, edited, reopened
#
# You can adjust the behavior by modifying this file.
name: Send GitHub Action trigger data to Slack workflow
on:
  issues:
    types:
      - opened
      - edited
      - reopened
  issue_comment:
    types:
      - created
      - edited

jobs:
  slack:
    runs-on: ubuntu-latest
    name: Trigger slack workflow
    steps:
    - name: slack-send
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "issueUrl" : ${{ github.event.issue.url }}
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
